/* Generated By:JJTree: Do not edit this line. ASTAsignacion.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTAsignacion extends SimpleNode {
  private String name;
  public ASTAsignacion(int id) {
    super(id);
  }

  public String toString() {
    return "Asignacion para el identificador: " + this.name;
  }

  public void setName(String n) {
    this.name = n;
  }

}
/* JavaCC - OriginalChecksum=85675b2554a1c063450ada122e7ffbb4 (do not edit this line) */
