/* Generated By:JJTree: Do not edit this line. ASTAsignacionD.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAsignacionD extends SimpleNode {
  public ASTAsignacionD(int id) {
    super(id);
  }

  public ASTAsignacionD(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5990a3a7016ce53f0540752767c756ea (do not edit this line) */
