/* Generated By:JJTree: Do not edit this line. ASTAsignacionD.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTAsignacionD extends SimpleNode {
  public ASTAsignacionD(int id) {
    super(id);
  }

  public ASTAsignacionD(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=daf0e05a651cdf250273390dcba659f7 (do not edit this line) */
