/* Generated By:JJTree: Do not edit this line. ASTCondi_inicio.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCondi_inicio extends SimpleNode {
  public ASTCondi_inicio(int id) {
    super(id);
  }

  public ASTCondi_inicio(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4f7b9a28f9b1aa5ab22f69f77eb9f1ed (do not edit this line) */
