/* Generated By:JJTree: Do not edit this line. ASTCondicion_RepitoHQ.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCondicion_RepitoHQ extends SimpleNode {
  public ASTCondicion_RepitoHQ(int id) {
    super(id);
  }

  public ASTCondicion_RepitoHQ(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=15ee725a18980b6fcd4bf6e7b2e8036c (do not edit this line) */
