/* Generated By:JJTree: Do not edit this line. ASTCodigo.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCodigo extends SimpleNode {
  public ASTCodigo(int id) {
    super(id);
  }

  public ASTCodigo(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=91f746e0c16c1fdac90f5b972cd21cd5 (do not edit this line) */
