/* Generated By:JJTree: Do not edit this line. ASTCiclo_RepitoMientras.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCiclo_RepitoMientras extends SimpleNode {
  public ASTCiclo_RepitoMientras(int id) {
    super(id);
  }

  public ASTCiclo_RepitoMientras(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1aac6a961ec01a739ba3d746a371430b (do not edit this line) */
