/* Generated By:JJTree: Do not edit this line. ASTCiclo_RepitoHastaQue.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCiclo_RepitoHastaQue extends SimpleNode {
  public ASTCiclo_RepitoHastaQue(int id) {
    super(id);
  }

  public ASTCiclo_RepitoHastaQue(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f860e1e1e5d05957435429c2e7b27ef7 (do not edit this line) */
