/* Generated By:JJTree: Do not edit this line. ASTCodigo.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCodigo extends SimpleNode {
  public ASTCodigo(int id) {
    super(id);
  }

  public ASTCodigo(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d523c1510924ebe19eef27275a2ba58 (do not edit this line) */
