/* Generated By:JJTree: Do not edit this line. ASTCondicion_RepitoHQ.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCondicion_RepitoHQ extends SimpleNode {
  public ASTCondicion_RepitoHQ(int id) {
    super(id);
  }

  public ASTCondicion_RepitoHQ(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=677b783bd7648b575a4e33b112f12fc1 (do not edit this line) */
