/* Generated By:JJTree: Do not edit this line. ASTCondicion_RepitoHQ.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCondicion_RepitoHQ extends SimpleNode {
  public ASTCondicion_RepitoHQ(int id) {
    super(id);
  }

  public ASTCondicion_RepitoHQ(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ffb112e3f4bb9d98acf8656c2b6c9a43 (do not edit this line) */
