/* Generated By:JJTree: Do not edit this line. ASTCiclo_RepitoMientras.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCiclo_RepitoMientras extends SimpleNode {
  public ASTCiclo_RepitoMientras(int id) {
    super(id);
  }

  public ASTCiclo_RepitoMientras(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=06f651c7a453ff9f0d176ca3680e9271 (do not edit this line) */
