/* Generated By:JJTree: Do not edit this line. ASTComparadores.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTComparadores extends SimpleNode {
  private String name;
  public ASTComparadores(int id) {
    super(id);
  }

  /*public ASTComparadores(Compilabob p, int id) {
    super(p, id);
  }*/
  
  public String toString() {
    switch(this.name){
        case "<":{
          return "Operador menor que: " + this.name;
        }
        case ">":{
          return "Operador mayor que: " + this.name;
        }
        case "<=":{
          return "Operador menor o igual: " + this.name;
        }
        case ">=":{
          return "Operador mayor o igual:" + this.name;
        }
        case "=":{
          return "Operador igual que:" + this.name;
        }
        case "!=":{
          return "Operador diferente de:" + this.name;
        }  
        default:
        return "Error: " + this.name;
 }
}

public void setName(String n) {
  this.name = n;
}

}

/* JavaCC - OriginalChecksum=4d0bb8b6afaa11f8fefc0a47d5cd6a2b (do not edit this line) */
