/* Generated By:JJTree: Do not edit this line. ASTCondi_inicio.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCondi_inicio extends SimpleNode {
  public ASTCondi_inicio(int id) {
    super(id);
  }

  public ASTCondi_inicio(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0341ee59152b2c8fc68747b766e5fd9 (do not edit this line) */
