/* Generated By:JJTree: Do not edit this line. ASTCiclo_RepitoHastaQue.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCiclo_RepitoHastaQue extends SimpleNode {
  public ASTCiclo_RepitoHastaQue(int id) {
    super(id);
  }

  public ASTCiclo_RepitoHastaQue(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=600d2e8b00259142bcb60ae15e75f33a (do not edit this line) */
