/* Generated By:JJTree: Do not edit this line. ASTCuerpo.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCuerpo extends SimpleNode {
  public ASTCuerpo(int id) {
    super(id);
  }

  public ASTCuerpo(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6af1c9fdd02db4fa9488fc17f07da032 (do not edit this line) */
