/* Generated By:JJTree: Do not edit this line. ASTCondi_inicio.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCondi_inicio extends SimpleNode {
  public ASTCondi_inicio(int id) {
    super(id);
  }

  public ASTCondi_inicio(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=40466c8c3ce871c8032607d636b40143 (do not edit this line) */
