/* Generated By:JJTree: Do not edit this line. ASTCondi_limite.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCondi_limite extends SimpleNode {
  public ASTCondi_limite(int id) {
    super(id);
  }

  public ASTCondi_limite(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73f30b1b6e1db9a49d4f6eda97c53483 (do not edit this line) */
