/* Generated By:JJTree: Do not edit this line. ASTConcatenacion.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTConcatenacion extends SimpleNode {
  public ASTConcatenacion(int id) {
    super(id);
  }

  public ASTConcatenacion(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9e7740054aafd6b156877dd64438ce5b (do not edit this line) */
