/* Generated By:JJTree: Do not edit this line. ASTCondi_limite.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCondi_limite extends SimpleNode {
  public ASTCondi_limite(int id) {
    super(id);
  }

  public ASTCondi_limite(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2be2189c02edc611ec0d5140934546b1 (do not edit this line) */
