/* Generated By:JJTree: Do not edit this line. ASTComparadores.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTComparadores extends SimpleNode {
  public ASTComparadores(int id) {
    super(id);
  }

  public ASTComparadores(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4d0bb8b6afaa11f8fefc0a47d5cd6a2b (do not edit this line) */
