/* Generated By:JJTree: Do not edit this line. ASTCondi_limite.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCondi_limite extends SimpleNode {
  public ASTCondi_limite(int id) {
    super(id);
  }

  public ASTCondi_limite(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f04ba0e59d28fcd47d5f6c5413e2930c (do not edit this line) */
