/* Generated By:JJTree: Do not edit this line. ASTCuerpo.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCuerpo extends SimpleNode {
  public ASTCuerpo(int id) {
    super(id);
  }

  public ASTCuerpo(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8254f9471190cb13a97bf44b0012f0b1 (do not edit this line) */
