/* Generated By:JJTree: Do not edit this line. ASTCuerpo.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCuerpo extends SimpleNode {
  public ASTCuerpo(int id) {
    super(id);
  }

  public ASTCuerpo(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df40a390fcf067a493ba742ed695e03a (do not edit this line) */
