/* Generated By:JJTree: Do not edit this line. ASTCodigo.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCodigo extends SimpleNode {
  public ASTCodigo(int id) {
    super(id);
  }

  public ASTCodigo(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2d5953d356ff0ac96d689a9b2a16353d (do not edit this line) */
