/* Generated By:JJTree: Do not edit this line. ASTConcatenacion.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConcatenacion extends SimpleNode {
  public ASTConcatenacion(int id) {
    super(id);
  }

  public ASTConcatenacion(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fd2d6ee42236ff894192f346e291d55d (do not edit this line) */
