/* Generated By:JJTree: Do not edit this line. ASTConcatenacion.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTConcatenacion extends SimpleNode {
  public ASTConcatenacion(int id) {
    super(id);
  }

  public ASTConcatenacion(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fdfebbc44c53f4a8617cbcdf00536d9a (do not edit this line) */
