/* Generated By:JJTree: Do not edit this line. ASTCiclo_RepitoMientras.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCiclo_RepitoMientras extends SimpleNode {
  public ASTCiclo_RepitoMientras(int id) {
    super(id);
  }

  public ASTCiclo_RepitoMientras(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3114c196ea142c8735260ae798bdcfab (do not edit this line) */
