/* Generated By:JJTree: Do not edit this line. ASTDecide.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTDecide extends SimpleNode {
  public ASTDecide(int id) {
    super(id);
  }

  public ASTDecide(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c7f246bdbe0677972b6c50e6ba9310aa (do not edit this line) */
