/* Generated By:JJTree: Do not edit this line. ASTDecide.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDecide extends SimpleNode {
  public ASTDecide(int id) {
    super(id);
  }

  public ASTDecide(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bb3135c505fc8f269bc9eddad4a6362d (do not edit this line) */
