/* Generated By:JJTree: Do not edit this line. ASTDataType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTDataType extends SimpleNode {
  private String name;
  public ASTDataType(int id) {
    super(id);
  }

  public String toString() {
    return "Valor de variable : " + this.name;
  }

  public void setName(String n) {
    this.name = n;
  }

}
/* JavaCC - OriginalChecksum=7647453e68efbe8107d7646b54e60a14 (do not edit this line) */
