/* Generated By:JJTree: Do not edit this line. ASTDecide.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTDecide extends SimpleNode {
  public ASTDecide(int id) {
    super(id);
  }

  public ASTDecide(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=16627fa32dac50fabb0576a330151e8d (do not edit this line) */
