/* Generated By:JJTree: Do not edit this line. ASTErrorNOFIN.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTErrorNOFIN extends SimpleNode {
  public ASTErrorNOFIN(int id) {
    super(id);
  }

  public ASTErrorNOFIN(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b83ca39d3376d730026b4ae8c2e3cab5 (do not edit this line) */
