/* Generated By:JJTree: Do not edit this line. ASTELSE.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTELSE extends SimpleNode {
  public ASTELSE(int id) {
    super(id);
  }

  public ASTELSE(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=819c695635b82eb604baa1e45e50e197 (do not edit this line) */
