/* Generated By:JJTree: Do not edit this line. ASTErrorNoinicio.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTErrorNoinicio extends SimpleNode {
  public ASTErrorNoinicio(int id) {
    super(id);
  }

  public ASTErrorNoinicio(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=361df3354d8ac6d54af1ceb92fd8687a (do not edit this line) */
