/* Generated By:JJTree: Do not edit this line. ASTerrorFinlinea.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerrorFinlinea extends SimpleNode {
  public ASTerrorFinlinea(int id) {
    super(id);
  }

  public ASTerrorFinlinea(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8bc67d0670bb898668c70a16caf3ac48 (do not edit this line) */
