/* Generated By:JJTree: Do not edit this line. ASTExpresion.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExpresion extends SimpleNode {
  public ASTExpresion(int id) {
    super(id);
  }

  public ASTExpresion(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7777f28382c6b96ebf34f08c5653e35f (do not edit this line) */
