/* Generated By:JJTree: Do not edit this line. ASTErrorNoinicio.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTErrorNoinicio extends SimpleNode {
  public ASTErrorNoinicio(int id) {
    super(id);
  }

  public ASTErrorNoinicio(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f29ae73c5d62dbef645611324340fa0 (do not edit this line) */
