/* Generated By:JJTree: Do not edit this line. ASTErrorNOFIN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTErrorNOFIN extends SimpleNode {
  public ASTErrorNOFIN(int id) {
    super(id);
  }

  public ASTErrorNOFIN(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3b7b33d167b8e98a602c2b0dfab3371 (do not edit this line) */
