/* Generated By:JJTree: Do not edit this line. ASTerror_skipto.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTerror_skipto extends SimpleNode {
  public ASTerror_skipto(int id) {
    super(id);
  }

  public ASTerror_skipto(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c320cdf1a81215ae8893e4077324166 (do not edit this line) */
