/* Generated By:JJTree: Do not edit this line. ASTerror.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerror extends SimpleNode {
  public ASTerror(int id) {
    super(id);
  }

  public ASTerror(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a4f7c873afd3931eba668493a2f4dfc7 (do not edit this line) */
