/* Generated By:JJTree: Do not edit this line. ASTErrorNoSepINICIO.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTErrorNoSepINICIO extends SimpleNode {
  public ASTErrorNoSepINICIO(int id) {
    super(id);
  }

  public ASTErrorNoSepINICIO(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c8f8a874ae4978c3817c362d382488aa (do not edit this line) */
