/* Generated By:JJTree: Do not edit this line. ASTerrorDOBLElinea.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerrorDOBLElinea extends SimpleNode {
  public ASTerrorDOBLElinea(int id) {
    super(id);
  }

  public ASTerrorDOBLElinea(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4df17b9343e8677c22b95e9817af625d (do not edit this line) */
