/* Generated By:JJTree: Do not edit this line. ASTErrorNoinicio.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTErrorNoinicio extends SimpleNode {
  public ASTErrorNoinicio(int id) {
    super(id);
  }

  public ASTErrorNoinicio(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=67b5393768a2ea1f28dad2e3168286de (do not edit this line) */
