/* Generated By:JJTree: Do not edit this line. ASTExpresionL.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExpresionL extends SimpleNode {
  public ASTExpresionL(int id) {
    super(id);
  }

  public ASTExpresionL(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2667f42587fad92db7f312ef8df0e194 (do not edit this line) */
