/* Generated By:JJTree: Do not edit this line. ASTELSE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTELSE extends SimpleNode {
  public ASTELSE(int id) {
    super(id);
  }

  public ASTELSE(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4477ce4f489efbab2612000c002073f3 (do not edit this line) */
