/* Generated By:JJTree: Do not edit this line. ASTerrorFinlinea.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTerrorFinlinea extends SimpleNode {
  public ASTerrorFinlinea(int id) {
    super(id);
  }

  public ASTerrorFinlinea(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=17cf296b08896271bd82a84386212a79 (do not edit this line) */
