/* Generated By:JJTree: Do not edit this line. ASTerror_skipto.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTerror_skipto extends SimpleNode {
  public ASTerror_skipto(int id) {
    super(id);
  }

  public ASTerror_skipto(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=857b69095b7247ebcf93b69b9a965f1c (do not edit this line) */
