/* Generated By:JJTree: Do not edit this line. ASTErrorNoSepINICIO.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTErrorNoSepINICIO extends SimpleNode {
  public ASTErrorNoSepINICIO(int id) {
    super(id);
  }

  public ASTErrorNoSepINICIO(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=51ca6e9d195f49d957cd220b6237f330 (do not edit this line) */
