/* Generated By:JJTree: Do not edit this line. ASTErrorNoSepFINAL.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTErrorNoSepFINAL extends SimpleNode {
  public ASTErrorNoSepFINAL(int id) {
    super(id);
  }

  public ASTErrorNoSepFINAL(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7308aece07d01cbc417ad1f5873c7639 (do not edit this line) */
