/* Generated By:JJTree: Do not edit this line. ASTerrorFinlinea.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTerrorFinlinea extends SimpleNode {
  public ASTerrorFinlinea(int id) {
    super(id);
  }

  public ASTerrorFinlinea(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6a177df67d0baa61c5d6d12c2ddcdf86 (do not edit this line) */
