/* Generated By:JJTree: Do not edit this line. ASTerror.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTerror extends SimpleNode {
  public ASTerror(int id) {
    super(id);
  }

  public ASTerror(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8eafafd688cfe6dc6e005bb441613e5c (do not edit this line) */
