/* Generated By:JJTree: Do not edit this line. ASTerrorDOBLElinea.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTerrorDOBLElinea extends SimpleNode {
  public ASTerrorDOBLElinea(int id) {
    super(id);
  }

  public ASTerrorDOBLElinea(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec665f07841607a30c13ba6d59e5cdeb (do not edit this line) */
