/* Generated By:JJTree: Do not edit this line. ASTErrorNoSepFINAL.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTErrorNoSepFINAL extends SimpleNode {
  public ASTErrorNoSepFINAL(int id) {
    super(id);
  }

  public ASTErrorNoSepFINAL(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e7fc691a4d3a16bea98ef1d7adebbccc (do not edit this line) */
