/* Generated By:JJTree: Do not edit this line. ASTerrorDOBLElinea.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTerrorDOBLElinea extends SimpleNode {
  public ASTerrorDOBLElinea(int id) {
    super(id);
  }

  public ASTerrorDOBLElinea(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=08a9c4ef982c3a0efd0b821d0b41f878 (do not edit this line) */
