/* Generated By:JJTree: Do not edit this line. ASTErrorNOFIN.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTErrorNOFIN extends SimpleNode {
  public ASTErrorNOFIN(int id) {
    super(id);
  }

  public ASTErrorNOFIN(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bd2828e355c59198d93c82b1780c7570 (do not edit this line) */
