/* Generated By:JJTree: Do not edit this line. ASTerror.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTerror extends SimpleNode {
  public ASTerror(int id) {
    super(id);
  }

  public ASTerror(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9715913c33ec0710006a5f20f3ebdbd7 (do not edit this line) */
