/* Generated By:JJTree: Do not edit this line. ASTErrorNoSepFINAL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTErrorNoSepFINAL extends SimpleNode {
  public ASTErrorNoSepFINAL(int id) {
    super(id);
  }

  public ASTErrorNoSepFINAL(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=83cd1e79dedde88bdd64db49ef9db914 (do not edit this line) */
