/* Generated By:JJTree: Do not edit this line. ASTErrorNoSepINICIO.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTErrorNoSepINICIO extends SimpleNode {
  public ASTErrorNoSepINICIO(int id) {
    super(id);
  }

  public ASTErrorNoSepINICIO(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=57bbaa58eb9f7f39a7cbd3a61275f1e4 (do not edit this line) */
