/* Generated By:JJTree: Do not edit this line. ASTExpresion.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpresion extends SimpleNode {
  public ASTExpresion(int id) {
    super(id);
  }

  public ASTExpresion(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5cf0057f8cd74ba324260e9f9c5d9977 (do not edit this line) */
