/* Generated By:JJTree: Do not edit this line. ASTExpresion.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTExpresion extends SimpleNode {
  public ASTExpresion(int id) {
    super(id);
  }

  public ASTExpresion(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b702518ddddf3494b997a2f8aded08c5 (do not edit this line) */
