/* Generated By:JJTree: Do not edit this line. ASTELSE.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTELSE extends SimpleNode {
  public ASTELSE(int id) {
    super(id);
  }

  public ASTELSE(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d809c0e38b9eb8d8022b991d87fee97d (do not edit this line) */
