/* Generated By:JJTree: Do not edit this line. ASTFactor.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFactor extends SimpleNode {
  public ASTFactor(int id) {
    super(id);
  }

  public ASTFactor(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fa88d9ebb9cfa75be6fb3139ff205ab5 (do not edit this line) */
