/* Generated By:JJTree: Do not edit this line. ASTFactor.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFactor extends SimpleNode {
  public ASTFactor(int id) {
    super(id);
  }

  public ASTFactor(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=56078b31820a0c791ba6dd1b8f1464c1 (do not edit this line) */
