/* Generated By:JJTree: Do not edit this line. ASTFactorR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFactorR extends SimpleNode {
  public ASTFactorR(int id) {
    super(id);
  }

  public ASTFactorR(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bc07040a3cf0ee3da9bf5f9566f70ef9 (do not edit this line) */
