/* Generated By:JJTree: Do not edit this line. ASTFactorR.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFactorR extends SimpleNode {
  public ASTFactorR(int id) {
    super(id);
  }

  public ASTFactorR(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f2c145c56c744aa923c2a9efeda78a65 (do not edit this line) */
