/* Generated By:JJTree: Do not edit this line. ASTFactorL.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFactorL extends SimpleNode {
  public ASTFactorL(int id) {
    super(id);
  }

  public ASTFactorL(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8090f227d0463c5f1ea2dde990cf531e (do not edit this line) */
