/* Generated By:JJTree: Do not edit this line. ASTFactorL.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFactorL extends SimpleNode {
  public ASTFactorL(int id) {
    super(id);
  }

  public ASTFactorL(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ab92d7637386e3e408b877efc0d712fc (do not edit this line) */
