/* Generated By:JJTree: Do not edit this line. ASTFactorR.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFactorR extends SimpleNode {
  public ASTFactorR(int id) {
    super(id);
  }

  public ASTFactorR(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2cdc6a0eaf6708cd9c6776b94df752a1 (do not edit this line) */
