/* Generated By:JJTree: Do not edit this line. ASTFactorL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFactorL extends SimpleNode {
  public ASTFactorL(int id) {
    super(id);
  }

  public ASTFactorL(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=422d5fa238d4742b781768990793dfdf (do not edit this line) */
