/* Generated By:JJTree: Do not edit this line. ASTIF.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTIF extends SimpleNode {
  public ASTIF(int id) {
    super(id);
  }

  public ASTIF(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cebb8a42b687f2d9d775e17909cd45c6 (do not edit this line) */
