/* Generated By:JJTree: Do not edit this line. ASTIF.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTIF extends SimpleNode {
  public ASTIF(int id) {
    super(id);
  }

  public ASTIF(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c303e0e9da1ac472c097653ccec23a32 (do not edit this line) */
