/* Generated By:JJTree: Do not edit this line. ASTLogicos.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTLogicos extends SimpleNode {
  public ASTLogicos(int id) {
    super(id);
  }

  public ASTLogicos(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=20e086310b2f55a84a7f726060559117 (do not edit this line) */
