/* Generated By:JJTree: Do not edit this line. ASTLEER.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTLEER extends SimpleNode {
  private String name;
  public ASTLEER(int id) {
    super(id);
  }
  public String toString() {
    return "INPUT Scanner: " + this.name;
  }

  public void setName(String n) {
    this.name = n;
  }

}
/* JavaCC - OriginalChecksum=8084be63638a6f0c1f6e7f40595306d2 (do not edit this line) */
