/* Generated By:JJTree: Do not edit this line. ASTLogicos.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogicos extends SimpleNode {
  public ASTLogicos(int id) {
    super(id);
  }

  public ASTLogicos(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=649925d99d99a2777618f94e3f929c3e (do not edit this line) */
