/* Generated By:JJTree: Do not edit this line. ASTMensaje.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMensaje extends SimpleNode {
  public ASTMensaje(int id) {
    super(id);
  }

  public ASTMensaje(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8d5754200efa53fb215c08f8801e0ace (do not edit this line) */
