/* Generated By:JJTree: Do not edit this line. ASTMuestra.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTMuestra extends SimpleNode {
  public ASTMuestra(int id) {
    super(id);
  }

  public ASTMuestra(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba5569f91442f76630093784d5003e2c (do not edit this line) */
