/* Generated By:JJTree: Do not edit this line. ASTMensaje.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTMensaje extends SimpleNode {
  public ASTMensaje(int id) {
    super(id);
  }

  public ASTMensaje(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a14aec020f17fac2d90b9a5838d28a9 (do not edit this line) */
