/* Generated By:JJTree: Do not edit this line. ASTMensaje.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTMensaje extends SimpleNode {
  public ASTMensaje(int id) {
    super(id);
  }

  public ASTMensaje(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5c4eeba91dc9c4647f1bc4e20b03e081 (do not edit this line) */
