/* Generated By:JJTree: Do not edit this line. ASTMuestra.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMuestra extends SimpleNode {
  public ASTMuestra(int id) {
    super(id);
  }

  public ASTMuestra(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=af75cd3c8d1f6d9eb16fdde54b072c45 (do not edit this line) */
