/* Generated By:JJTree: Do not edit this line. ASTMenoss.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTMenoss extends SimpleNode {
  private String name;
  public ASTMenoss(int id) {
    super(id);
  }

  public String toString() {
    return "Operador matematico: " + this.name;
  }

  public void setName(String n) {
    this.name = n;
  }

}
/* JavaCC - OriginalChecksum=87167ee3635b92ee92d91f1b4ff48315 (do not edit this line) */
