/* Generated By:JJTree: Do not edit this line. ASTOpComparacion.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTOpComparacion extends SimpleNode {
  public ASTOpComparacion(int id) {
    super(id);
  }

  public ASTOpComparacion(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=503e57b60e73679eff27a9274c203e7f (do not edit this line) */
