/* Generated By:JJTree: Do not edit this line. ASTOperadores.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperadores extends SimpleNode {
  public ASTOperadores(int id) {
    super(id);
  }

  public ASTOperadores(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d652f6ee21ce5569f944b82822cb4181 (do not edit this line) */
