/* Generated By:JJTree: Do not edit this line. ASTOpComparacion.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTOpComparacion extends SimpleNode {
  public ASTOpComparacion(int id) {
    super(id);
  }

  public ASTOpComparacion(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4be52e89da3c201428759cc4944fee2a (do not edit this line) */
