/* Generated By:JJTree: Do not edit this line. ASTOperadores.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTOperadores extends SimpleNode {
  public ASTOperadores(int id) {
    super(id);
  }

  public ASTOperadores(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=301b511a8f338bf9e8766697d1d02629 (do not edit this line) */
