/* Generated By:JJTree: Do not edit this line. ASTOpComparacion.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOpComparacion extends SimpleNode {
  public ASTOpComparacion(int id) {
    super(id);
  }

  public ASTOpComparacion(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=deabdcf60a7e40d5fe6a43d63819e33a (do not edit this line) */
