/* Generated By:JJTree: Do not edit this line. ASTPrimario.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrimario extends SimpleNode {
  public ASTPrimario(int id) {
    super(id);
  }

  public ASTPrimario(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bd6bdab0aadd683511b0afdc4d64c6fd (do not edit this line) */
