/* Generated By:JJTree: Do not edit this line. ASTPrimario.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPrimario extends SimpleNode {
  public ASTPrimario(int id) {
    super(id);
  }

  public ASTPrimario(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=16f333bec63e82e7c7a9e0cea7a988d7 (do not edit this line) */
