/* Generated By:JJTree: Do not edit this line. ASTPrimario.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPrimario extends SimpleNode {
  public ASTPrimario(int id) {
    super(id);
  }

  public ASTPrimario(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec15f3adda4722acbf044cc1428b1e9a (do not edit this line) */
