/* Generated By:JJTree: Do not edit this line. ASTsentencias.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTsentencias extends SimpleNode {
  public ASTsentencias(int id) {
    super(id);
  }

  public ASTsentencias(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=571ff30608df71d028c4ccd2ceee7f08 (do not edit this line) */
