/* Generated By:JJTree: Do not edit this line. ASTsentencias.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsentencias extends SimpleNode {
  public ASTsentencias(int id) {
    super(id);
  }

  public ASTsentencias(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=718c1bdb15215f2b2bbc5544fab53169 (do not edit this line) */
