/* Generated By:JJTree: Do not edit this line. ASTsentencias.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTsentencias extends SimpleNode {
  public ASTsentencias(int id) {
    super(id);
  }

  public ASTsentencias(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=768ec25d8755020959395e21fd8147b3 (do not edit this line) */
