/* Generated By:JJTree: Do not edit this line. ASTTermino.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTTermino extends SimpleNode {
  public ASTTermino(int id) {
    super(id);
  }

  public ASTTermino(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8a639492288eb4733edd810ade45e2f9 (do not edit this line) */
