/* Generated By:JJTree: Do not edit this line. ASTTermino.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTermino extends SimpleNode {
  public ASTTermino(int id) {
    super(id);
  }

  public ASTTermino(Compilabob p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b4566e75d17dcc67398bf14d9f830169 (do not edit this line) */
