/* Generated By:JJTree: Do not edit this line. ASTVariable_IDEN.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTVariable_IDEN extends SimpleNode {
  private String name;
  public ASTVariable_IDEN(int id) {
    super(id);
  }

  public String toString() {
    return "Identificador: " + this.name;
  }

  public void setName(String n) {
    this.name = n;
  }

}
/* JavaCC - OriginalChecksum=78789279429f4bf85fc7c73b673bb70d (do not edit this line) */
