/* Generated By:JavaCC: Do not edit this line. CompilabobTreeConstants.java Version 4.1d1 */
public interface CompilabobTreeConstants
{
  public int JJTCODIGO = 0;
  public int JJTCUERPO = 1;
  public int JJTSENTENCIAS = 2;
  public int JJTMUESTRA = 3;
  public int JJTMENSAJE = 4;
  public int JJTCONCATENACION = 5;
  public int JJTDECIDE = 6;
  public int JJTIF = 7;
  public int JJTELSE = 8;
  public int JJTCICLO_REPITOHASTAQUE = 9;
  public int JJTCONDICION_REPITOHQ = 10;
  public int JJTCONDI_INICIO = 11;
  public int JJTCONDI_LIMITE = 12;
  public int JJTCICLO_REPITOMIENTRAS = 13;
  public int JJTDECLARACION = 14;
  public int JJTASIGNACIOND = 15;
  public int JJTASIGNACION = 16;
  public int JJTEXPRESION = 17;
  public int JJTTERMINO = 18;
  public int JJTFACTOR = 19;
  public int JJTPRIMARIO = 20;
  public int JJTMAS_MENOS = 21;
  public int JJTMENOSS = 22;
  public int JJTMDM = 23;
  public int JJTOPCOMPARACION = 24;
  public int JJTFACTORL = 25;
  public int JJTFACTORR = 26;
  public int JJTVARIABLE_IDEN = 27;
  public int JJTDATATYPE = 28;
  public int JJTCOMPARADORES = 29;
  public int JJTLEER = 30;
  public int JJTVARIABLE_DATO = 31;
  public int JJTOPERADORES = 32;
  public int JJTERROR_SKIPTO = 33;
  public int JJTERROR = 34;
  public int JJTERRORFINLINEA = 35;
  public int JJTERRORDOBLELINEA = 36;
  public int JJTERRORNOINICIO = 37;
  public int JJTERRORNOSEPINICIO = 38;
  public int JJTERRORNOSEPFINAL = 39;
  public int JJTERRORNOFIN = 40;


  public String[] jjtNodeName = {
    "Codigo",
    "Cuerpo",
    "sentencias",
    "Muestra",
    "Mensaje",
    "Concatenacion",
    "Decide",
    "IF",
    "ELSE",
    "Ciclo_RepitoHastaQue",
    "Condicion_RepitoHQ",
    "Condi_inicio",
    "Condi_limite",
    "Ciclo_RepitoMientras",
    "Declaracion",
    "AsignacionD",
    "Asignacion",
    "Expresion",
    "Termino",
    "Factor",
    "Primario",
    "Mas_menos",
    "Menoss",
    "MDM",
    "OpComparacion",
    "FactorL",
    "FactorR",
    "Variable_IDEN",
    "DataType",
    "Comparadores",
    "LEER",
    "Variable_dato",
    "Operadores",
    "error_skipto",
    "error",
    "errorFinlinea",
    "errorDOBLElinea",
    "ErrorNoinicio",
    "ErrorNoSepINICIO",
    "ErrorNoSepFINAL",
    "ErrorNOFIN",
  };
}
/* JavaCC - OriginalChecksum=4990925ef908d2b8f7d504554c237c97 (do not edit this line) */
